### ISSUE TITLE
Compatibility with WSL2

### ISSUE THREAD

**Issue by lefevrej** [bloomberg/memray#156]
I used to work with memray on an ubuntu env with WSL2. When I upgraded memray from 1.0.3 to 1.2.0 I was able to launch a script with run but not to generate the flamegraph report.

Here is the associated error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lefevrej/.local/lib/python3.8/site-packages/memray/__main__.py", line 6, in <module>
    sys.exit(main())
  File "/home/lefevrej/.local/lib/python3.8/site-packages/memray/commands/__init__.py", line 124, in main
    arg_values.entrypoint(arg_values, parser)
  File "/home/lefevrej/.local/lib/python3.8/site-packages/memray/commands/common.py", line 117, in run
    self.write_report(result_path, output_file, args.show_memory_leaks, **kwargs)
  File "/home/lefevrej/.local/lib/python3.8/site-packages/memray/commands/common.py", line 76, in write_report
    reader = FileReader(os.fspath(result_path), report_progress=True)
  File "src/memray/_memray.pyx", line 503, in memray._memray.FileReader.__cinit__
  File "src/memray/_memray.pyx", line 410, in memray._memray.ProgressIndicator.__init__
AttributeError: type object 'Progress' has no attribute 'get_default_columns'
```

**Comment by godlygeek** [comment]
What version of the `rich` library is installed? You may need to `python3.8 -m pip install --user --upgrade rich` - it looks like we need at least 11.2.0 for `get_default_columns`
